security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            stateless: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            json_login:
                check_path: /authentication_token
                # JSON property that holds username or email
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        #- { path: ^/refresh_token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/authentication_token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/profile, roles: ROLE_USER }

    # prevent symfony from wrapping our custom AccountStatusExceptions in a generic
    # BadCredentialsException as this would prevent accurate error messages
    hide_user_not_found: false