framework:
    default_locale: '%default_locale%'
    translator:
        default_path: '%kernel.project_dir%/translations_custom'
        paths:
            - '%kernel.project_dir%/translations'
        fallbacks:
            - de
