twig:
    paths:
        - '%kernel.project_dir%/templates_custom'
        - '%kernel.project_dir%/templates'
        - '%kernel.project_dir%/public/images'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
