twig:
    paths:
        # add this folder to your project and uncomment the line to overwrite
        # templates from the main project with your own and still keep the
        # project upradable & conflictfree
        #- '%kernel.project_dir%/templates_custom'
        - '%kernel.project_dir%/templates'
        - '%kernel.project_dir%/public/images'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    # fix deprecation: The "twig.exception_controller" configuration key has
    # been deprecated in Symfony 4.4, set it to "null" and use
    # "framework.error_controller" configuration key instead.
    exception_controller: