image: vrokdd/php:api
pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - composer install && chmod ugo+x bin/* && export APP_ENV=test
          - until bin/console doctrine:query:sql "SELECT 1" > /dev/null 2>&1; do sleep 1; done
          - vendor/bin/phpunit
        services:
          - mysql
          - rabbitmq
    - step:
        script:
          - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          - docker build --target api_platform_php -t jschumanndd/hpo:latest .
          - docker push jschumanndd/hpo:latest
          - docker build --target api_platform_nginx -t jschumanndd/hpo:nginx .
          - docker push jschumanndd/hpo:nginx
        services:
          - docker

definitions:
  services:
    mysql:
      image: mariadb:latest
      variables:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: hpo_test
        MYSQL_USER: hpo_test
        MYSQL_PASSWORD: hpo_test
    rabbitmq:
      image: rabbitmq:3
      variables:
        RABBITMQ_DEFAULT_USER: messenger
        RABBITMQ_DEFAULT_PASS: messenger
