version: '2'
services:
  mysql-hpo:
    image: mariadb:latest
    container_name: mysql-hpo
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hpo_test
      MYSQL_USER: hpo_test
      MYSQL_PASSWORD: hpo_test

  rabbitmq-hpo:
    image: rabbitmq:3-management
    container_name: rabbitmq-hpo
    hostname: rabbitmq
    ports:
      - 8090:15672
    environment:
      RABBITMQ_DEFAULT_USER: messenger
      RABBITMQ_DEFAULT_PASS: messenger

  php-hpo:
    build: php
    container_name: php-hpo
    links:
      - mysql-hpo
      - rabbitmq-hpo
    volumes:
      - ../:/srv/api
    environment:
      APP_ENV: test
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal
      START_CRON: "false"
      START_MESSENGER: "true"
      START_FPM: "false"