version: '2'
services:
  mysql-hpo:
    image: mariadb:latest
    container_name: mysql-hpo
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hpo_test
      MYSQL_USER: hpo_test
      MYSQL_PASSWORD: hpo_test

  php-hpo:
    build: php
    container_name: php-hpo
    links:
      - mysql-hpo
    volumes:
      # /projects muss in der Virtualbox als Shared Folder gemounted sein
      - /projects/hpo-backend/:/var/www/html
    extra_hosts:
      - host.vbox.internal:192.168.178.47
    environment:
      APP_ENV: test
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.vbox.internal
      START_CRON: "false"
      START_MESSENGER: "true"
      START_FPM: "false"